services:


  caddy:
    container_name: caddy
    image: caddy:2
    restart: unless-stopped
    # environment:
      # Controls what port the Caddy server binds to inside its container.
      # PRIVATE_BACKEND_URL: ${PRIVATE_BACKEND_URL:-http://backend:8080}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/srv/frontend/dist
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      #- avatars:/srv/frontend/avatars

  backend:
    container_name: backend
    hostname: backend
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - avatars:/var/images/avatars

  db:
    image: postgres:17-alpine
    container_name: db
    hostname: db
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  avatars:
  caddy_data:
  caddy_logs: