services:
  backend-8080:
    container_name: backend-8080
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: